export type Timestamp = string | number | null
export interface Match { eventId: number; setId: number; roundLabel: string | null; displayScore: string | null; state: number | null; startedAt: number | null; completedAt: number | null; winnerId: number | null; slots: { entrantId: number | null; name: string | null }[]; sources: ('player' | 'seed' | 'final')[]; observedAt: Timestamp; url: string }
export interface EventSummary { eventId: number | null; eventSlug: string; eventName: string; tournamentName: string; videogameName: string | null; active: boolean; eventState: string | null; interest: 'follow' | 'event' | 'none'; snapshotAt: Timestamp; lastError: string | null; notificationError: string | null; liveCount: number }
export interface Player { id: number; playerId: number | null; playerName: string; entrantId: number | null; status: string | null; placement: number | null; placementIsFinal: boolean; lastSetScoreText: string | null; lastSetRoundLabel: string | null; capturedAt: Timestamp; isPreset: boolean }
export interface Seed { seedNum: number; entrantId: number; entrantName: string; phaseId: number; phaseName: string }
export interface Detail { servedAt: Timestamp; event: EventSummary; players: Player[]; seeds: Seed[]; finalPhase: { id: number; name: string; numSeeds: number; entrants: Seed[]; standings: { placement: number; entrantId: number; entrantName: string }[] } | null; liveSets: Match[]; recentSets: Match[] }
export interface Operation { id: string; type: string; status: 'queued' | 'running' | 'succeeded' | 'failed'; createdAt: Timestamp; startedAt: Timestamp; finishedAt: Timestamp; result: unknown; error: string | null }
export interface Board { players: (Player & { eventId: number; eventName: string })[]; servedAt: Timestamp; events: EventSummary[]; liveSets: Match[]; recentSets: Match[]; pendingCount: number; runtime: { busy: boolean; queuedTasks: number; notificationError: string | null; pollingEnabled: boolean; nextPollAt: Timestamp; fastPollingEnabled: boolean; nextFastPollAt: Timestamp; lastAttemptAt: Timestamp; lastSuccessAt: Timestamp; lastFullSuccessAt: Timestamp; lastError: string | null; stopReason: string | null }; operation: Operation | null }
export interface Pending { id: number; eventSlug: string; eventName: string; tournamentName: string; videogameName: string; playerNames: string[] }
export interface Following { servedAt: Timestamp; players: Player[]; preferences: { videogameId: number; videogameName: string }[]; eventInterests: { eventSlug: string; expiresAt: Timestamp }[]; pending: Pending[]; featuredSeedCount: number }
export interface Candidate { playerId: number; playerName: string; userId: number | null; gamerTag: string | null }
export interface Discovered { isFollowed: boolean; interest: 'follow' | 'event' | 'dismissed' | 'none'; eventId: number; eventSlug: string; eventName: string; tournamentName: string; videogameName: string }
export interface SetsPage { servedAt: Timestamp; sets: Match[]; nextCursor: string | null }
