<script setup lang="ts">
import type { Following } from '../types'
defineProps<{ following: Following | null }>()
defineEmits<{ manage: [] }>()
</script>
<template>
  <header class="page-heading"><div><p class="eyebrow">你的观赛范围</p><h1>关注管理</h1><p class="muted">与 Telegram 共用选手、游戏偏好和本届关注。</p></div><button class="primary" @click="$emit('manage')">添加与设置</button></header>
  <p v-if="!following" class="empty">正在读取关注信息…</p>
  <div v-else class="following-grid"><section class="panel"><div class="section-heading"><h2>关注选手</h2><span class="count">{{ following.players.length }}</span></div><div v-for="player in following.players" :key="player.id" class="following-row"><strong><span class="accent">★</span> {{ player.playerName }}</strong><span class="tag">{{ player.isPreset ? '固定名单' : '手动添加' }}</span></div><p v-if="!following.players.length" class="empty">暂无关注选手</p><p class="meta">固定名单随配置同步；新添加选手等待下一次比赛采集。</p></section><div class="stack"><section class="panel"><div class="section-heading"><h2>长期关注游戏</h2></div><div class="tags"><span v-for="preference in following.preferences" :key="preference.videogameId" class="chip">{{ preference.videogameName }}</span></div><p v-if="!following.preferences.length" class="empty small">暂无长期关注游戏</p><p class="meta">允许后续发现的该游戏项目；监控暂停时不会持续发现。</p></section><section class="panel"><div class="section-heading"><h2>本届项目关注</h2></div><div v-for="interest in following.eventInterests" :key="interest.eventSlug" class="interest-row"><a :href="`https://www.start.gg/${interest.eventSlug}`" target="_blank" rel="noopener noreferrer">{{ interest.eventSlug }} ↗</a><p class="meta">持续关注至本项目实际完赛</p></div><p v-if="!following.eventInterests.length" class="empty small">暂无有效的本届项目关注</p></section><section class="panel"><div class="section-heading"><h2>全局种子关注</h2><span class="tag">{{ following.featuredSeedCount ? `Top ${following.featuredSeedCount}` : '关闭' }}</span></div><p class="meta">影响全部当前监控项目，历史已采集赛果继续保留。</p><button class="text-button" @click="$emit('manage')">调整档位 →</button></section></div></div>
</template>
