<script setup lang="ts">
import { computed, onMounted, onUnmounted, shallowRef, useTemplateRef } from 'vue'
import type { BoardData } from '../composables/useBoardData'
import type { Discovered } from '../types'
import { stopReason, time } from '../format'
const props = defineProps<{ data: BoardData }>()
const dialog = useTemplateRef<HTMLDialogElement>('dialog')
const section = shallowRef('discover')
const keyword = shallowRef('')
const eventLink = shallowRef('')
const playerInput = shallowRef('')
const seedDraft = shallowRef(0)
const selected = shallowRef<Discovered | null>(null)
const manualConfirm = shallowRef(false)
const discoveredInterest = shallowRef<'follow' | 'event'>('event')
const pendingChoice = shallowRef<{ id: number; name: string; action: string } | null>(null)
const found = computed(() => props.data.discovered.value?.filter(event => `${event.tournamentName} ${event.eventName} ${event.videogameName}`.toLowerCase().includes(keyword.value.toLowerCase())))
const currentNames = computed(() => props.data.board.value?.events.filter(event => event.active).map(event => event.eventName).join('、') || '暂无当前监控项目')
const op = computed(() => props.data.operation.value)
const busy = computed(() => props.data.busy.value || props.data.board.value?.runtime.busy === true)
function open(target = 'discover') {
  section.value = target
  seedDraft.value = props.data.following.value?.featuredSeedCount ?? 0
  selected.value = null
  manualConfirm.value = false
  pendingChoice.value = null
  if (!dialog.value?.open) { history.pushState({ ...history.state, ftgDrawer: true }, '', location.href); dialog.value?.showModal() }
}
function close() { dialog.value?.close(); if (history.state?.ftgDrawer) history.back() }
function popstate() { if (dialog.value?.open) dialog.value.close() }
onMounted(() => window.addEventListener('popstate', popstate))
onUnmounted(() => window.removeEventListener('popstate', popstate))
defineExpose({ open })
async function start() { const eventSlug = selected.value?.eventSlug ?? eventLink.value.trim(); await props.data.run('/monitoring/start', { eventSlug, ...(selected.value ? { interest: discoveredInterest.value } : {}) }) }
async function interest() { const value = pendingChoice.value!; await props.data.run(`/interests/${value.id}`, { action: value.action }); pendingChoice.value = null }
</script>
<template>
  <dialog ref="dialog" class="operations-dialog" aria-labelledby="operations-title" @cancel.prevent="close" @click="($event.target === dialog) && close()">
    <div class="drawer-content"><header class="drawer-heading"><div><p class="eyebrow">观赛控制台</p><h2 id="operations-title">赛事与监控</h2></div><button aria-label="关闭设置面板" @click="close">关闭 ×</button></header>
      <nav class="tabs drawer-tabs" aria-label="管理内容"><button :class="{ active: section === 'discover' }" @click="section = 'discover'">发现赛事</button><button :class="{ active: section === 'pending' }" @click="section = 'pending'">待确认 {{ data.following.value?.pending.length || '' }}</button><button :class="{ active: section === 'players' }" @click="section = 'players'">添加选手</button><button :class="{ active: section === 'settings' }" @click="section = 'settings'">监控设置</button></nav>
      <div v-if="data.actionError.value" class="error" role="alert">{{ data.actionError.value }}</div>
      <div v-if="op" class="operation-feedback" :class="{ error: op.status === 'failed' }" role="status"><strong>{{ op.status === 'queued' ? (op.type === 'pause' || op.type === '/monitoring/pause' ? '暂停中 · 当前采集结束后生效' : '已接受 · 等待当前任务完成') : op.status === 'running' ? '正在执行，请稍候…' : op.status === 'failed' ? '操作失败' : '操作已完成' }}</strong><p v-if="op.error">{{ op.error }}</p><p v-if="op.status === 'succeeded' && op.type === 'add-player'">已加入关注，等待同步。</p><p class="meta">{{ op.finishedAt ? `完成于 ${time(op.finishedAt)}` : '关闭面板不会取消已接受的操作。' }}</p></div>
      <section v-show="section === 'discover'" class="drawer-section"><h3>发现你的下一场比赛</h3><p class="muted">发现街霸 6 候选赛事和关注选手的活动赛事，不是全站搜索。</p><button class="primary" :disabled="busy" @click="data.run('/discover')">{{ busy ? '任务进行中…' : '发现赛事' }}</button><template v-if="data.discovered.value !== null"><label class="field">筛选本次发现结果<input v-model="keyword" placeholder="大会、项目或游戏名称"></label><div v-for="event in found" :key="event.eventSlug" class="discovery-row"><p class="meta">{{ event.tournamentName }}</p><strong>{{ event.eventName }}</strong><p class="meta">{{ event.videogameName }} · {{ event.interest === 'follow' ? '已长期关注游戏' : event.interest === 'event' ? '已关注本届此项目' : event.interest === 'dismissed' ? '本届已忽略' : '待选择关注范围' }}</p><div class="actions"><button :disabled="busy" @click="selected = event; manualConfirm = false; discoveredInterest = 'follow'">长期关注游戏</button><button v-if="event.interest !== 'follow'" :disabled="busy" @click="selected = event; manualConfirm = false; discoveredInterest = 'event'">仅关注本届此项目</button><button v-if="event.interest === 'none'" :disabled="busy" @click="data.run('/discover/dismiss', { eventSlug: event.eventSlug })">本届不关注</button></div></div><p v-if="!found?.length" class="empty small">本次发现中没有匹配结果，不代表全球没有比赛。</p></template><div class="divider"></div><h3>输入项目链接</h3><p class="muted">切换当前监控项目，并长期关注该项目所属游戏。</p><form @submit.prevent="manualConfirm = true; selected = null"><label class="field">start.gg 项目链接<input v-model="eventLink" type="text" required placeholder="https://www.start.gg/tournament/…/event/…"></label><button :disabled="busy || !eventLink.trim()">确认切换范围</button></form><div v-if="selected || manualConfirm" class="confirmation"><h3>切换并启动监控</h3><strong>{{ selected?.eventName || eventLink }}</strong><p>这会替换当前活动监控项目，{{ selected && discoveredInterest === 'event' ? '仅关注本届此项目' : '长期关注对应游戏' }}。首次采集成功后开启轮询。</p><p class="meta">当前监控：{{ currentNames }}</p><div class="actions"><button class="primary" :disabled="busy" @click="start">{{ busy ? '启动中…' : '切换并启动监控' }}</button><button @click="selected = null; manualConfirm = false">取消</button></div></div></section>
      <section v-show="section === 'pending'" class="drawer-section"><h3>确认感兴趣的比赛</h3><p class="muted">“仅关注本届”只适用于此比赛项目，不包含同大会其他项目。</p><div v-for="pending in data.following.value?.pending" :key="pending.id" class="discovery-row"><p class="meta">{{ pending.tournamentName }} · {{ pending.videogameName }}</p><h3>{{ pending.eventName }}</h3><p class="meta">相关选手：{{ pending.playerNames.join('、') || '未提供' }}</p><div class="actions"><button :disabled="busy" @click="pendingChoice = { id: pending.id, name: pending.eventName, action: 'follow' }">长期关注游戏</button><button :disabled="busy" @click="pendingChoice = { id: pending.id, name: pending.eventName, action: 'event' }">仅关注本届此项目</button><button :disabled="busy" @click="data.run(`/interests/${pending.id}`, { action: 'dismiss' })">本届不关注</button></div></div><p v-if="!data.following.value?.pending.length" class="empty">当前没有待确认项目</p><div v-if="pendingChoice" class="confirmation"><h3>{{ pendingChoice.action === 'follow' ? '长期关注游戏并启动' : '仅关注本届此项目并启动' }}</h3><strong>{{ pendingChoice.name }}</strong><p>将按允许的发现结果替换活动监控集合，完成首次采集后才开启监控。</p><p class="meta">当前监控：{{ currentNames }}</p><div class="actions"><button class="primary" :disabled="busy" @click="interest">确认并启动</button><button @click="pendingChoice = null">取消</button></div></div></section>
      <section v-show="section === 'players'" class="drawer-section"><h3>添加关注选手</h3><p class="muted">输入 start.gg 用户链接，或当前监控项目内的选手名。</p><form @submit.prevent="data.run('/players/resolve', { input: playerInput.trim() })"><label class="field">用户链接或选手名<input v-model="playerInput" required placeholder="用户链接 / Gamer tag"></label><button class="primary" :disabled="busy || !playerInput.trim()">解析选手身份</button></form><template v-if="data.candidates.value !== null"><div v-for="candidate in data.candidates.value" :key="candidate.playerId" class="discovery-row"><strong>{{ candidate.playerName }}</strong><p class="meta">{{ candidate.gamerTag }} · Player #{{ candidate.playerId }}<span v-if="candidate.userId"> · User #{{ candidate.userId }}</span></p><button :disabled="busy" @click="data.run('/players', { playerId: candidate.playerId })">关注此选手</button></div><p v-if="!data.candidates.value.length" class="empty">没有找到对应选手，请核对用户链接或当前项目内姓名。</p></template></section>
      <section v-show="section === 'settings'" class="drawer-section"><h3>比赛采集</h3><p>{{ data.board.value?.runtime.pollingEnabled ? '定时采集已开启' : '监控已暂停或停止' }}</p><p v-if="data.board.value?.runtime.stopReason" class="meta">停止原因：{{ stopReason(data.board.value.runtime.stopReason) }}</p><dl v-if="data.board.value" class="runtime-grid"><dt>最近采集成功</dt><dd>{{ time(data.board.value.runtime.lastSuccessAt) }}</dd><dt>最近完整同步</dt><dd>{{ time(data.board.value.runtime.lastFullSuccessAt) }}</dd><dt>下次固定采集</dt><dd>{{ time(data.board.value.runtime.nextPollAt) }}</dd><dt>下次加速采集</dt><dd>{{ time(data.board.value.runtime.nextFastPollAt) }}</dd></dl><div class="actions"><button :disabled="data.submitting.value || (busy && (!data.board.value?.runtime.pollingEnabled || op?.type === 'pause' || op?.type === '/monitoring/pause'))" @click="data.run(data.board.value?.runtime.pollingEnabled ? '/monitoring/pause' : '/monitoring/resume')">{{ data.board.value?.runtime.pollingEnabled ? '暂停监控' : '恢复监控' }}</button><button :disabled="busy" @click="data.run('/sync')">立即同步比赛</button></div><p class="meta">暂停保留数据；单次同步可能产生 Telegram 比赛通知，不会自动恢复已暂停监控。</p><div class="divider"></div><h3>全局种子关注</h3><p class="muted">影响全部当前监控项目。同步成功后生效，关闭不删除已采集赛果。</p><label class="field">种子档位<select v-model.number="seedDraft"><option :value="0">关闭</option><option :value="16">Top 16</option><option :value="32">Top 32</option></select></label><button class="primary" :disabled="busy || seedDraft === data.following.value?.featuredSeedCount" @click="data.run('/settings/featured-seeds', { count: seedDraft }, 'PUT')">保存并同步种子</button><p class="meta">当前生效：{{ data.following.value?.featuredSeedCount ? `Top ${data.following.value.featuredSeedCount}` : '关闭' }}</p></section>
    </div>
  </dialog>
</template>
