<script setup lang="ts">
import { reactive } from 'vue'
import type { ReminderHistoryItem, ReminderHistoryResponse } from '../types'
import { dateTime, now } from '../format'
import { deliveryText, historyActionText, historyKindText } from '../labels'
const props = defineProps<{ data: ReminderHistoryResponse | null; filters: { from: string; to: string; kind: string }; loading: boolean }>()
const emit = defineEmits<{ filter: [value: Record<string, string>]; more: []; copy: [item: ReminderHistoryItem] }>()
const draft = reactive({ ...props.filters })
function range(days: number) { draft.from = now().subtract(days - 1, 'day').format('YYYY-MM-DD'); draft.to = now().format('YYYY-MM-DD'); emit('filter', { ...draft }) }
</script>
<template><div><p class="eyebrow">每一件小事，都有来处</p><div class="page-heading"><div><h1>提醒历史</h1><p>已发送和已完成，分别留下真实记录。</p></div></div><div class="actions range-actions"><button class="outline-button" @click="range(7)">最近 7 天</button><button class="outline-button" @click="range(30)">最近 30 天</button></div><form class="filter-panel" @submit.prevent="emit('filter', { ...draft })"><label class="field">计划日期 · 从<input v-model="draft.from" type="date" required></label><label class="field">计划日期 · 至<input v-model="draft.to" type="date" :min="draft.from" required></label><label class="field">类型<select v-model="draft.kind"><option value="all">全部类型</option><option value="once">一次性</option><option value="run">循环当次</option><option value="rule">循环规则</option><option value="vitamin">维生素</option><option value="work-checkin">打卡</option><option value="bus">下车</option></select></label><button class="primary" :disabled="loading">筛选</button></form><p v-if="data" class="results-summary">{{ data.total }} 条记录<span v-if="loading"> · 正在更新…</span></p><div class="history-list"><article v-for="item in data?.items" :key="item.id" class="history-item"><div class="history-date"><time v-if="item.triggerAt" :datetime="item.triggerAt">{{ dateTime(item.triggerAt) }}</time><span v-else>{{ item.date }} · 时间未记录</span><span>{{ historyKindText[item.kind] }}</span></div><div class="history-copy"><h3>{{ item.text }}</h3><div class="tag-row"><span class="tag">{{ historyActionText[item.action] }}</span><span class="tag">{{ deliveryText[item.deliveryStatus] }}</span></div><p v-if="item.occurredAt">操作记录于 {{ dateTime(item.occurredAt) }}</p><p v-if="item.note">{{ item.note }}</p><p v-if="item.error" class="error">{{ item.error }}</p><button v-if="item.kind === 'once'" class="text-button" @click="emit('copy', item)">复制为新提醒</button></div></article></div><div v-if="data && !data.items.length" class="empty"><h3>这段时间没有相应记录</h3><p>可以调整日期或提醒类型。</p></div><p v-if="!data" class="loading-placeholder">{{ loading ? '正在读取历史…' : '历史记录尚未读取。' }}</p><button v-if="data && data.nextOffset !== null" class="load-more outline-button" :disabled="loading" @click="emit('more')">{{ loading ? '正在读取…' : '继续查看' }}</button></div></template>
