<script setup lang="ts">
import { reactive } from 'vue'
import type { Feedback, ReminderItem, ReminderListResponse } from '../types'
import ReminderCard from '../components/ReminderCard.vue'
const props = defineProps<{ data: ReminderListResponse | null; filters: { q: string; status: string; from: string; to: string }; loading: boolean; pending: Record<string, boolean>; feedback: Record<string, Feedback> }>()
const emit = defineEmits<{ filter: [value: Record<string, string>]; more: []; create: []; detail: [item: ReminderItem]; edit: [item: ReminderItem]; action: [item: ReminderItem, action: 'done' | 'skip' | 'snooze'] }>()
const draft = reactive({ ...props.filters })
function clear() { Object.assign(draft, { q: '', status: 'active', from: '', to: '' }); emit('filter', { ...draft }) }
</script>
<template><div><p class="eyebrow">留给未来的自己</p><div class="page-heading"><div><h1>全部提醒</h1><p>查看和整理每一条一次性安排。</p></div></div><nav class="view-links"><RouterLink to="/reminders" aria-current="page">一次性提醒</RouterLink><RouterLink to="/rules">循环规则</RouterLink><RouterLink to="/life">生活提醒</RouterLink></nav><form class="filter-panel" @submit.prevent="emit('filter', { ...draft })"><label class="field filter-search">查找内容<input v-model="draft.q" type="search" placeholder="输入提醒关键词"></label><label class="field">状态<select v-model="draft.status"><option value="active">有效提醒</option><option value="all">全部状态</option><option value="scheduled">待触发</option><option value="snoozed">已延期</option><option value="awaiting">已发送待确认</option><option value="done">已完成</option><option value="cancelled">已取消</option><option value="missed">已错过</option><option value="failed">发送失败</option><option value="unknown">历史结果不明</option></select></label><label class="field">从<input v-model="draft.from" type="date"></label><label class="field">至<input v-model="draft.to" type="date" :min="draft.from || undefined"></label><div class="actions"><button class="primary" :disabled="loading">筛选</button><button class="text-button" type="button" @click="clear">清除条件</button></div></form><p v-if="data" class="results-summary">{{ data.total }} 条提醒<span v-if="loading"> · 正在更新…</span></p><div class="card-stack"><ReminderCard v-for="item in data?.items" :key="item.key" :item="item" :busy="pending[item.key]" :feedback="feedback[item.key]" @detail="emit('detail', $event)" @edit="emit('edit', $event)" @action="(entry, action) => emit('action', entry, action)" /></div><div v-if="data && !data.items.length" class="empty"><h3>没有符合条件的提醒</h3><p>可以调整筛选，或新建一条安排。</p><div class="actions"><button class="outline-button" @click="clear">清除筛选</button><button class="primary" @click="emit('create')">新建提醒</button></div></div><p v-if="!data" class="loading-placeholder">{{ loading ? '正在读取提醒…' : '提醒列表尚未读取。' }}</p><button v-if="data?.nextOffset !== null && data" class="load-more outline-button" :disabled="loading" @click="emit('more')">{{ loading ? '正在读取…' : '继续查看' }}</button></div></template>
