<script setup lang="ts">
import type { Feedback, ReminderRulesResponse, ReminderRuleView } from '../types'
import { dateTime } from '../format'
import { ruleStatusText } from '../labels'
import AppIcon from '../components/AppIcon.vue'
defineProps<{ data: ReminderRulesResponse | null; status: string; loading: boolean; pending: Record<string, boolean>; feedback: Record<string, Feedback> }>()
const emit = defineEmits<{ filter: [value: Record<string, string>]; create: []; detail: [rule: ReminderRuleView]; action: [rule: ReminderRuleView, action: 'pause' | 'resume'] }>()
</script>
<template><div><p class="eyebrow">让小事成为习惯</p><div class="page-heading"><div><h1>循环规则</h1><p>管理重复安排，也能看到每一次提醒。</p></div><button class="outline-button" @click="emit('create')"><AppIcon name="plus" />新建规则</button></div><nav class="view-links"><RouterLink to="/reminders">一次性提醒</RouterLink><RouterLink to="/rules" aria-current="page">循环规则</RouterLink><RouterLink to="/life">生活提醒</RouterLink></nav><label class="field inline-field">规则状态<select :value="status" @change="emit('filter', { status: ($event.target as HTMLSelectElement).value })"><option value="active">运行中</option><option value="paused">已暂停</option><option value="cancelled">已结束</option><option value="all">全部规则</option></select></label><p v-if="loading" class="muted" role="status">正在更新规则…</p><div class="card-stack"><article v-for="rule in data?.rules" :key="rule.id" class="reminder-card"><div class="task-main"><span class="task-icon"><AppIcon name="repeat" /></span><div class="task-copy"><button class="task-title" @click="emit('detail', rule)">{{ rule.text }}</button><p>{{ rule.summary }}</p><p>下一次 {{ dateTime(rule.nextTriggerAt) }}<span v-if="rule.timezone !== 'Asia/Shanghai'"> · 原时区 {{ rule.timezone }}</span></p><div class="tag-row"><span class="tag" :class="{ 'tag--green': rule.status === 'active' }">{{ ruleStatusText[rule.status] }}</span></div></div></div><p v-if="rule.error" class="error">{{ rule.error }}</p><p v-if="feedback[`rule:${rule.id}`]" :class="feedback[`rule:${rule.id}`]!.error ? 'error' : 'success'" role="status">{{ feedback[`rule:${rule.id}`]!.text }}</p><div class="task-footer"><button class="text-button" @click="emit('detail', rule)">查看规则与记录<AppIcon name="arrow" /></button><button v-if="rule.status !== 'cancelled'" class="outline-button" :disabled="pending[`rule:${rule.id}`]" @click="emit('action', rule, rule.status === 'active' ? 'pause' : 'resume')">{{ pending[`rule:${rule.id}`] ? '处理中…' : rule.status === 'active' ? '暂停' : '恢复' }}</button></div></article></div><div v-if="data && !data.rules.length" class="empty"><h3>这里还没有对应的规则</h3><p>每天读书、每周整理，都可以慢慢安排。</p><button class="outline-button" @click="emit('create')">新建循环规则</button></div></div></template>
