<script setup lang="ts">
import type { Feedback, LifeAction, LifeItem } from '../types'
import { clock, dateTime } from '../format'
import { lifeConfirmText, lifeIcon, lifeStatusText } from '../labels'
import AppIcon from './AppIcon.vue'
defineProps<{ item: LifeItem; busy?: boolean; feedback?: Feedback; settingsLink?: boolean }>()
const emit = defineEmits<{ action: [item: LifeItem, action: LifeAction]; settings: [item: LifeItem] }>()
</script>
<template>
  <article class="reminder-card life-card" :class="{ 'reminder-card--waiting': item.status === 'awaiting' }" :aria-busy="busy"><div class="task-main"><span class="task-icon" :class="{ clay: item.status === 'awaiting' }"><AppIcon :name="lifeIcon[item.kind]" /></span><div class="task-copy"><button class="task-title" @click="emit('settings', item)">{{ item.title }}</button><p v-if="item.nextTriggerAt">下次 {{ dateTime(item.nextTriggerAt) }}</p><p v-else-if="item.windowStart && item.windowEnd">{{ clock(item.windowStart) }}–{{ clock(item.windowEnd) }} 之间 · 时刻尚未确定</p><p v-else-if="item.firstTriggerAt">计划 {{ dateTime(item.firstTriggerAt) }}</p><div class="tag-row"><span class="tag">生活专项</span><span class="tag" :class="{ 'tag--clay': item.status === 'awaiting', 'tag--green': item.status === 'scheduled' || item.status === 'confirmed' }">{{ lifeStatusText[item.status] }}</span><span v-if="!item.enabled" class="tag">长期已关闭</span></div></div></div><p class="item-note">{{ item.rule }}</p><p v-if="item.lastSentAt" class="item-note">最近提醒 {{ dateTime(item.lastSentAt) }}<span v-if="item.sentCount !== null"> · 已提醒 {{ item.sentCount }} 次</span></p><p v-if="item.reason" class="item-note">{{ item.reason }}</p><p v-if="item.error" class="error" role="alert">{{ item.error }}</p><div v-if="item.actions.length || settingsLink || feedback" class="task-footer"><p v-if="feedback" :class="feedback.error ? 'error' : 'success'" role="status">{{ feedback.text }}</p><div class="actions"><button v-if="item.actions.includes('confirm')" class="primary small" :disabled="busy" @click="emit('action', item, 'confirm')">{{ busy ? '处理中…' : lifeConfirmText[item.kind] }}</button><button v-if="item.actions.includes('snooze')" class="outline-button" :disabled="busy" @click="emit('action', item, 'snooze')">30 分钟后</button><button v-if="settingsLink" class="text-button" @click="emit('settings', item)">今天与规则<AppIcon name="arrow" /></button></div></div></article>
</template>
